// Runtime version (baked in at build time)
export const VERSION = '3.260227.5';

// Runtime fallback version (no npm registry access — N=0 signals local/dev build)
// Canonical versions are generated by scripts/version.ts at build time: 3.YYMMDD.N
export function generateVersion(): string {
  const now = new Date();
  const yy = now.getFullYear().toString().slice(-2);
  const mm = (now.getMonth() + 1).toString().padStart(2, '0');
  const dd = now.getDate().toString().padStart(2, '0');
  return `3.${yy}${mm}${dd}.0`;
}
