import { homedir } from 'os';
import { join } from 'path';
import { existsSync, readFileSync, writeFileSync, mkdirSync, appendFileSync } from 'fs';
import * as readline from 'readline';

export interface ShortcutsOptions {
  tmux?: boolean;
  termux?: boolean;
  install?: boolean;
}

// Generate tmux.conf snippet for Warp-like shortcuts
export function generateTmuxConfig(): string {
  return `# Warp-like keyboard shortcuts (generated by genie-cli)
# To use: add to ~/.tmux.conf or source this file

# Ctrl+T: New window (tab) in current session
bind-key -n C-t new-window

# Ctrl+S: Vertical split (requires stty -ixon in shell rc)
bind-key -n C-s split-window -v

# Ctrl+H: Horizontal split
bind-key -n C-h split-window -h
`;
}

// Generate termux.properties snippet for extra keys
export function generateTermuxConfig(): string {
  return `# Warp-like extra keys (generated by genie-cli)
# To use: add to ~/.termux/termux.properties

# Extra keys row with F-keys for shortcuts
# F1=New Tab, F2=VSplit, F3=HSplit
extra-keys = [['ESC','TAB','CTRL','ALT','F1','F2','F3']]
`;
}

// Generate shell functions for bashrc/zshrc
export function generateShellFunctions(): string {
  return `# Warp-like shortcuts (generated by genie-cli)
# To use: add to ~/.bashrc or ~/.zshrc

# Disable Ctrl+S flow control (required for Ctrl+S to work in tmux)
stty -ixon 2>/dev/null

# Genie shortcuts (for Termux extra keys F1-F3)
genie-new-tab() {
  local session
  session=$(tmux display-message -p '#S' 2>/dev/null)
  if [ -n "$session" ]; then
    tmux new-window
  else
    echo "Not in a tmux session"
  fi
}

genie-vsplit() {
  if tmux display-message -p '#S' >/dev/null 2>&1; then
    tmux split-window -v
  else
    echo "Not in a tmux session"
  fi
}

genie-hsplit() {
  if tmux display-message -p '#S' >/dev/null 2>&1; then
    tmux split-window -h
  else
    echo "Not in a tmux session"
  fi
}

# Bind F1-F3 to genie shortcuts (works in Termux)
bind -x '"\eOP":"genie-new-tab"' 2>/dev/null   # F1
bind -x '"\eOQ":"genie-vsplit"' 2>/dev/null    # F2
bind -x '"\eOR":"genie-hsplit"' 2>/dev/null    # F3
`;
}

// Display all shortcuts in a readable format
export function displayShortcuts(): void {
  console.log(`
Warp-like Terminal Shortcuts for tmux + Termux

┌────────────┬────────────────────────────────────────┐
│ Shortcut   │ Action                                 │
├────────────┼────────────────────────────────────────┤
│ Ctrl+T     │ New tab (window) in current session    │
│ Ctrl+S     │ Vertical split in current session      │
│ Ctrl+H     │ Horizontal split in current session    │
└────────────┴────────────────────────────────────────┘

Termux Extra Keys (F1-F3):
  F1 → New tab       F2 → Vertical split
  F3 → Horizontal split

Commands:
  term shortcuts --tmux     Output tmux.conf snippet
  term shortcuts --termux   Output termux.properties snippet
  term shortcuts --install  Install to config files
`);
}

// Helper to prompt user
async function prompt(question: string): Promise<string> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim().toLowerCase());
    });
  });
}

// Check if content already exists in file
function contentExists(filePath: string, marker: string): boolean {
  if (!existsSync(filePath)) return false;
  const content = readFileSync(filePath, 'utf-8');
  return content.includes(marker);
}

// Install shortcuts to config files
export async function installShortcuts(): Promise<void> {
  const home = homedir();
  const marker = 'generated by genie-cli';

  console.log('Installing Warp-like shortcuts...\n');

  // 1. Install to tmux.conf
  const tmuxConf = join(home, '.tmux.conf');
  if (contentExists(tmuxConf, marker)) {
    console.log('✓ tmux.conf already has genie shortcuts');
  } else {
    const answer = await prompt(`Add shortcuts to ${tmuxConf}? [Y/n] `);
    if (answer !== 'n') {
      const content = '\n' + generateTmuxConfig();
      appendFileSync(tmuxConf, content);
      console.log(`✅ Added to ${tmuxConf}`);
    } else {
      console.log('⏭️ Skipped tmux.conf');
    }
  }

  // 2. Install to bashrc/zshrc
  const shellRc = existsSync(join(home, '.zshrc'))
    ? join(home, '.zshrc')
    : join(home, '.bashrc');

  if (contentExists(shellRc, marker)) {
    console.log(`✓ ${shellRc} already has genie shortcuts`);
  } else {
    const answer = await prompt(`Add shell functions to ${shellRc}? [Y/n] `);
    if (answer !== 'n') {
      const content = '\n' + generateShellFunctions();
      appendFileSync(shellRc, content);
      console.log(`✅ Added to ${shellRc}`);
    } else {
      console.log(`⏭️ Skipped ${shellRc}`);
    }
  }

  // 3. Install to termux.properties (if Termux detected)
  const termuxDir = join(home, '.termux');
  const termuxProps = join(termuxDir, 'termux.properties');
  const isTermux = existsSync(termuxDir) || process.env.TERMUX_VERSION;

  if (isTermux) {
    if (contentExists(termuxProps, marker)) {
      console.log('✓ termux.properties already has genie shortcuts');
    } else {
      const answer = await prompt(`Add extra keys to ${termuxProps}? [Y/n] `);
      if (answer !== 'n') {
        if (!existsSync(termuxDir)) {
          mkdirSync(termuxDir, { recursive: true });
        }
        const content = '\n' + generateTermuxConfig();
        appendFileSync(termuxProps, content);
        console.log(`✅ Added to ${termuxProps}`);
        console.log('   Run: termux-reload-settings');
      } else {
        console.log('⏭️ Skipped termux.properties');
      }
    }
  }

  console.log('\n✅ Installation complete!');
  console.log('\nNext steps:');
  console.log('  1. Reload tmux: tmux source ~/.tmux.conf');
  console.log('  2. Restart your shell or run: source ~/.bashrc');
  if (isTermux) {
    console.log('  3. Reload Termux: termux-reload-settings');
  }
}

// Check if shortcuts are installed in a file
export function isShortcutsInstalled(filePath: string): boolean {
  const marker = 'generated by genie-cli';
  return contentExists(filePath, marker);
}

// Remove content between markers from a file
function removeMarkedContent(filePath: string, marker: string): boolean {
  if (!existsSync(filePath)) return false;

  const content = readFileSync(filePath, 'utf-8');
  if (!content.includes(marker)) return false;

  // Split into lines and find the block to remove
  const lines = content.split('\n');
  const filteredLines: string[] = [];
  let inBlock = false;
  let blockStartIndex = -1;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.includes(marker) && !inBlock) {
      // Start of a marked block - find the comment start (could be previous line)
      inBlock = true;
      // Check if previous line is a blank line we should also remove
      if (blockStartIndex === -1 && filteredLines.length > 0 && filteredLines[filteredLines.length - 1].trim() === '') {
        filteredLines.pop();
      }
      continue;
    }
    if (inBlock) {
      // Check if this is the end of the block (empty line followed by non-genie content)
      if (line.trim() === '' && i + 1 < lines.length && !lines[i + 1].includes('genie')) {
        inBlock = false;
        continue;
      }
      // Check if this line is part of our genie config (has specific markers)
      const isGenieContent =
        line.includes('genie') ||
        line.includes('Ctrl+') ||
        line.includes('split-window') ||
        line.includes('new-window') ||
        line.includes('stty -ixon') ||
        line.includes('Warp-like') ||
        line.includes('bind-key -n') ||
        line.includes('extra-keys') ||
        line.includes('F1=') ||
        line.includes('bind -x') ||
        line.startsWith('#') && lines[i - 1]?.includes('genie');

      if (!isGenieContent && line.trim() !== '') {
        inBlock = false;
        filteredLines.push(line);
      }
      // Skip genie content lines
      continue;
    }
    filteredLines.push(line);
  }

  // Clean up trailing newlines
  while (filteredLines.length > 0 && filteredLines[filteredLines.length - 1].trim() === '') {
    filteredLines.pop();
  }

  // Add back one trailing newline if file had content
  const newContent = filteredLines.length > 0 ? filteredLines.join('\n') + '\n' : '';
  writeFileSync(filePath, newContent);
  return true;
}

// Uninstall shortcuts from config files
export async function uninstallShortcuts(): Promise<void> {
  const home = homedir();
  const marker = 'generated by genie-cli';

  console.log('Uninstalling Warp-like shortcuts...\n');

  // 1. Remove from tmux.conf
  const tmuxConf = join(home, '.tmux.conf');
  if (!contentExists(tmuxConf, marker)) {
    console.log('✓ tmux.conf has no genie shortcuts');
  } else {
    const answer = await prompt(`Remove shortcuts from ${tmuxConf}? [Y/n] `);
    if (answer !== 'n') {
      if (removeMarkedContent(tmuxConf, marker)) {
        console.log(`✅ Removed from ${tmuxConf}`);
      }
    } else {
      console.log('⏭️ Skipped tmux.conf');
    }
  }

  // 2. Remove from bashrc/zshrc
  const zshrc = join(home, '.zshrc');
  const bashrc = join(home, '.bashrc');

  // Check both files
  for (const shellRc of [zshrc, bashrc]) {
    if (!existsSync(shellRc)) continue;
    if (!contentExists(shellRc, marker)) {
      console.log(`✓ ${shellRc} has no genie shortcuts`);
    } else {
      const answer = await prompt(`Remove shell functions from ${shellRc}? [Y/n] `);
      if (answer !== 'n') {
        if (removeMarkedContent(shellRc, marker)) {
          console.log(`✅ Removed from ${shellRc}`);
        }
      } else {
        console.log(`⏭️ Skipped ${shellRc}`);
      }
    }
  }

  // 3. Remove from termux.properties (if Termux detected)
  const termuxDir = join(home, '.termux');
  const termuxProps = join(termuxDir, 'termux.properties');
  const isTermux = existsSync(termuxDir) || process.env.TERMUX_VERSION;

  if (isTermux) {
    if (!contentExists(termuxProps, marker)) {
      console.log('✓ termux.properties has no genie shortcuts');
    } else {
      const answer = await prompt(`Remove extra keys from ${termuxProps}? [Y/n] `);
      if (answer !== 'n') {
        if (removeMarkedContent(termuxProps, marker)) {
          console.log(`✅ Removed from ${termuxProps}`);
          console.log('   Run: termux-reload-settings');
        }
      } else {
        console.log('⏭️ Skipped termux.properties');
      }
    }
  }

  console.log('\n✅ Uninstallation complete!');
  console.log('\nNext steps:');
  console.log('  1. Reload tmux: tmux source ~/.tmux.conf');
  console.log('  2. Restart your shell or run: source ~/.bashrc');
  if (isTermux) {
    console.log('  3. Reload Termux: termux-reload-settings');
  }
}

// Main handler
export async function handleShortcuts(options: ShortcutsOptions): Promise<void> {
  if (options.tmux) {
    console.log(generateTmuxConfig());
  } else if (options.termux) {
    console.log(generateTermuxConfig());
  } else if (options.install) {
    await installShortcuts();
  } else {
    displayShortcuts();
  }
}
